name: Debug Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  DebugCheckout:
    runs-on: ubuntu-latest
    steps:
      - name: Clean workspace
        run: rm -rf ${{ github.workspace }}/*

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          path: ${{ github.workspace }}/my-custom-directory

      - name: List directory
        run: ls -al ${{ github.workspace }}/my-custom-directory
