name: Test Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  RunUnitTests:
    runs-on: ubuntu-latest
    steps:
      - name: Clean workspace
        run: rm -rf ${{ github.workspace }}/*

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          path: my-custom-directory

